#####  Configuration file for the chosen optical system


name:
    system_name: HYACAMEO
    
system_architecture:
    name: DD-CASSI   # or DD-CASSI
    lens_focal_length_1: 165000
    dispersive_element_1:
    # dispersive element caracteristics
        type: prism        # name of the dispersive element
        alpha_c: 49.441  # incident angle on the dispersive surface 			          -- in degrees
        delta_alpha_c: 0
        delta_beta_c: 0
        A: 60              # apex angle of the prism in degrees      (only used if type == 'prism')   -- in degrees
        m: 1               # grating order to consider         (only used if type == 'grating')       -- no units
        G: 160             # grating density                   (only used if type == 'grating')       -- in lines/mm
    lens_focal_length_2: 165000
    lens_focal_length_3: 165000
    dispersive_element_2:
    # dispersive element caracteristics
        type: prism        # name of the dispersive element
        alpha_c: 49.441  # incident angle on the dispersive surface 			          -- in degrees
        delta_alpha_c: 0
        delta_beta_c: 0
        A: 60              # apex angle of the prism in degrees      (only used if type == 'prism')   -- in degrees
        m: 1               # grating order to consider         (only used if type == 'grating')       -- no units
        G: 160             # grating density                   (only used if type == 'grating')       -- in lines/mm
    lens_focal_length_4: 165000
FOV:
# The field diaphragm dimensions

    # mode in which to define the FOV,
    field_of_view_mode : 1

    # if "field_of_view_mode" is 0 ,
    # using field of view mode in um
    FOV_ACT: 100   # field-of-view "across-track" (perpendicular to the movement direction when in pushbroom), it is paralell to the dispersion direction   -- in um
    FOV_ALT: 100   # field-of-view "along-track" (parallel to the movement direction when in pushbroom), it is perpendicular to the dispersion direction   -- in um
    FOV_center_ACT: 0
    FOV_center_ALT: 0

    # if "field_of_view_mode" is 1 ,
    #	using  [camera']['nb_of_camera_pixels_ACT'] and [camera']['nb_of_camera_pixels_ALT'] instead

spectral_range:
# the spectral range of the optical system

    lba_min: 450     # minimum wavelength -- in nm
    lba_max: 750      # maximum wavelength -- in nm


camera:
# camera caracteristics
    nb_of_camera_pixels_ACT: 30                  # nb_of_camera_pixels_ACT -- no units
    nb_of_camera_pixels_ALT: 10                  # nb_of_camera_pixels_ALT -- no units
    pixel_size: 4.8                              # pixel_size       -- in um   # A FAIRE , passer aux pixels rectangulaires ????

DMD:
# DMD caracteristics
    um_size: 5.4               # micromirror side size  -- in um
    nb_um_ALT: 500              # number of micromirrors in the direction perpendicular to the dispersion ("along-track" if used in pushbroom) -- no units
    nb_um_ACT: 1500             # number of micromirrors in the direction of the dispersion ("across-track" if used in pushbroom)              -- no units





    
