#####  Configuration file for the chosen optical system

infos:
    system name: HYACAMEO
    results directory: ./dimensionning_results

system architecture:
    type: SD-CASSI   # or DD-CASSI
    focal lens 1: 165000
    dispersive element 1:
    # dispersive element caracteristics
        type: prism        # name of the dispersive element
        delta alpha c: 0
        delta beta c: 0
        A: 60              # apex angle of the prism in degrees      (only used if type == 'prism')   -- in degrees
        m: 1               # grating order to consider         (only used if type == 'grating')       -- no units
        G: 160             # grating density                   (only used if type == 'grating')       -- in lines/mm
    focal lens 2: 165000
    focal lens 3: 165000
    dispersive element 2:
    # dispersive element caracteristics
        type: prism        # name of the dispersive element
        delta alpha c: 0
        delta beta c: 0
        A: 60              # apex angle of the prism in degrees      (only used if type == 'prism')   -- in degrees
        m: 1               # grating order to consider         (only used if type == 'grating')       -- no units
        G: 160             # grating density                   (only used if type == 'grating')       -- in lines/mm
    focal lens 4: 165000

spectral range:
# the spectral range of the optical system
    wavelength min: 450     # minimum wavelength -- in nm
    wavelength center: 550  # central wavelength -- in nm
    wavelength max: 750      # maximum wavelength -- in nm

camera:
# camera caracteristics
    number of pixels along dispersion: 55                  # nb_of_camera_pixels_ACT -- no units
    number of pixels across dispersion: 37                  # nb_of_camera_pixels_ALT -- no units
    pixel size: 200                              # pixel_size       -- in um   # A FAIRE , passer aux pixels rectangulaires ????

DMD:
# DMD caracteristics
    micromirror size: 5.4               # micromirror side size  -- in um
    number of micromirrors across dispersion: 500              # number of micromirrors in the direction perpendicular to the dispersion ("along-track" if used in pushbroom) -- no units
    number of micromirrors along dispersion: 1500             # number of micromirrors in the direction of the dispersion ("across-track" if used in pushbroom)              -- no units







