#####  Configuration file for the chosen optical system

infos:
    system name: HYACAMEO

system architecture:
    system type: DD-CASSI
    propagation type: simca
    focal lens: 200000
    dispersive element:
    # dispersive element caracteristics
        type: grating        # name of the dispersive element
        A: 60              # apex angle of the prism in degrees      (only used if type == 'prism')   -- in degrees
        m: 1               # grating order to consider         (only used if type == 'grating')       -- no units
        G: 150             # grating density                   (only used if type == 'grating')       -- in lines/mm
        delta alpha c: 0
        delta beta c: 0
        wavelength center: 550  # central wavelength -- in nm
detector:
    sampling across X: 201                  # sampling across X axis -- no units
    sampling across Y: 201                  # sampling across Y axis -- no units
    delta X: 40                             # delta X       -- in um
    delta Y: 40                              # delta Y       -- in um
SLM:
    sampling across X: 253                  # sampling across X axis -- no units
    sampling across Y: 201                  # sampling across Y axis -- no units
    delta X: 55                              # delta X       -- in um
    delta Y: 55                              # delta Y       -- in um

spectral range:
    wavelength min: 401     # minimum wavelength -- in nm
    wavelength max: 649      # maximum wavelength -- in nm
    number of spectral samples: 200
