#####  Configuration file for the chosen optical system

infos:
    results directory: ./data/results/

spectral range:
    wavelength min: 450     # minimum wavelength -- in nm
    wavelength max: 750      # maximum wavelength -- in nm

input grid sampling:
    sampling across X: 48                  # sampling across X axis -- no units
    sampling across Y: 51                  # sampling across Y axis -- no units
    delta X : 100                              # delta X       -- in um
    delta Y : 100                              # delta Y       -- in um

number of spectral samples: 30
