name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Add this line if you have a requirements.txt file

    - name: Run tests
      run: python tests.py  # Update this line to the path of your tests.py if it's not in the root directory

